# common/webcam_config.py
#
# AUTO-GENERATED by robot/test.py (camera calibration)
# Timestamp: 2026-01-09T14:10:40.156503
# Resolution: 1280 x 720
# RMS Error: 0.7784 pixels
#

import numpy as np

# ================================================================
#  Camera Configuration for Kinova Gen3 / RTSP Camera
#  Calibrated at resolution: 1280 x 720
# ================================================================

# ---- Intrinsic Parameters ----
fx = 1322.80671180
fy = 1283.88377334
cx = 617.34969573
cy = 242.52098146

camera_params = (fx, fy, cx, cy)

# ---- Distortion Coefficients (k1, k2, p1, p2, k3) ----
dist_coeffs = np.array([
    0.07809246,
    0.59312613,
    -0.00789068,
    -0.01396958,
    -4.42277109
])

# ---- AprilTag parameters ----
# IMPORTANT: Measure your tag accurately! Edge to edge of outer black border.
tag_size = 0.05         # meters - UPDATE THIS TO YOUR ACTUAL TAG SIZE
tag_family = "tag36h11"  # AprilTag family


# ---- Camera Matrix K ----
K = np.array([
    [fx, 0.0, cx],
    [0.0, fy, cy],
    [0.0, 0.0, 1.0]
])


# ---- RTSP Camera Stream ----
DEFAULT_ROBOT_IP = "192.168.1.10"

def rtsp_url(ip: str = DEFAULT_ROBOT_IP) -> str:
    """Build the RTSP URL for the Kinova Gen3 color stream."""
    return f"rtsp://{ip}/color"
