[pytest]
minversion = 7.0
testpaths = 
    tests/integration
    tests/units

markers =
    integration: tests that require a physical robot and real hardware connection
    units: tests that can be run without a physical robot, using mocks and stubs

